name: fluttertransoon
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+8
  cupertino_icons: ^0.1.2
  firebase_analytics: any
  firebase_messaging: 6.0.16
  google_sign_in: ^4.0.0
  firebase_auth: ^0.16.1
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  meta: ^1.1.6
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.4.0
  datetime_picker_formfield: ^1.0.0
  shared_preferences: ^0.5.6+1
  file_picker: ^1.12.0
  http: ^0.12.1
  async: ^2.4.1
  rflutter_alert: ^1.0.2
  flutter_rating_bar: ^3.0.1+1
  rating_dialog: ^1.0.0
  quick_feedback: ^0.1.1
  bottom_navy_bar: ^5.4.0
  flutter_money_formatter: ^0.8.3
  bubble_tab_indicator: "^0.1.4"
  flutter_multiselect: ^0.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/

    #dependencies:
    #flutter:
    # sdk: flutter

    # cupertino_icons: ^0.1.3

    #dev_dependencies:
    # flutter_test:
    #sdk: flutter

  #flutter:
  #uses-material-design: true
